# Generated by Django 4.2 on 2024-01-12 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('country_of_issue', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_issue', models.CharField(blank=True, max_length=50, null=True)),
                ('diabetes_management_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('treatement_approach', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('communication_method_for_patient', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_number', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_consultations', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type_of_diabetes', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_diagnosis', models.DateField(blank=True, null=True)),
                ('current_diabetes_medication', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_sugar_level', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_history', models.CharField(blank=True, max_length=50, null=True)),
                ('dietary_habits', models.CharField(blank=True, max_length=50, null=True)),
                ('physical_activity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('smoking_habits', models.CharField(blank=True, max_length=50, null=True)),
                ('alcohol_consumption', models.CharField(blank=True, max_length=50, null=True)),
                ('date_last_HbA1c_test_and_result', models.CharField(blank=True, max_length=50, null=True)),
                ('doctors', models.ManyToManyField(related_name='patients_treated', to='users.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(related_name='treated_by_doctors', to='users.patient'),
        ),
    ]
