# Generated by Django 4.2 on 2024-01-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctor_patient_doctor_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(null=True, related_name='treated_by_doctors', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(null=True, related_name='patients_treated', to='users.doctor'),
        ),
    ]
